### ISSUE TITLE
Issue in Android 5

### ISSUE THREAD

**Issue by adeds** [jimblackler/jsonschemafriend#23]
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/FileSystems;
       at net.jimblackler.jsonschemafriend.CacheLoader.<clinit>(CacheLoader.java:17)
       at net.jimblackler.jsonschemafriend.SchemaStore.<init>(SchemaStore.java:71)
       at net.jimblackler.jsonschemafriend.SchemaStore.<init>(SchemaStore.java:51)
```

since FileSystems is added in API version 26, it will crash on android version under 26

**Comment by sun-sky** [comment]
encounter Same Problem
